# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: the_roommate_app_development
  username: postgres
  password: Asdfdsa123Car
  host: localhost
# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: the_roommate_app_test
  username: postgres
  password: Asdfdsa123Car
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: uilenstede_roommate_app_production
  username: uilenstede_roommate_app
  password: <%= ENV['UILENSTEDE_ROOMMATE_APP_DATABASE_PASSWORD'] %>
